// Generated by gencpp from file lidar_imu_fusion/cloud_img.msg
// DO NOT EDIT!


#ifndef LIDAR_IMU_FUSION_MESSAGE_CLOUD_IMG_H
#define LIDAR_IMU_FUSION_MESSAGE_CLOUD_IMG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/PointCloud2.h>
#include <sensor_msgs/Image.h>

namespace lidar_imu_fusion
{
template <class ContainerAllocator>
struct cloud_img_
{
  typedef cloud_img_<ContainerAllocator> Type;

  cloud_img_()
    : header()
    , local_map()
    , img()  {
    }
  cloud_img_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , local_map(_alloc)
    , img(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _local_map_type;
  _local_map_type local_map;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _img_type;
  _img_type img;





  typedef boost::shared_ptr< ::lidar_imu_fusion::cloud_img_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_imu_fusion::cloud_img_<ContainerAllocator> const> ConstPtr;

}; // struct cloud_img_

typedef ::lidar_imu_fusion::cloud_img_<std::allocator<void> > cloud_img;

typedef boost::shared_ptr< ::lidar_imu_fusion::cloud_img > cloud_imgPtr;
typedef boost::shared_ptr< ::lidar_imu_fusion::cloud_img const> cloud_imgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_imu_fusion::cloud_img_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_imu_fusion::cloud_img_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lidar_imu_fusion::cloud_img_<ContainerAllocator1> & lhs, const ::lidar_imu_fusion::cloud_img_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.local_map == rhs.local_map &&
    lhs.img == rhs.img;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lidar_imu_fusion::cloud_img_<ContainerAllocator1> & lhs, const ::lidar_imu_fusion::cloud_img_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lidar_imu_fusion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lidar_imu_fusion::cloud_img_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_imu_fusion::cloud_img_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_imu_fusion::cloud_img_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_imu_fusion::cloud_img_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_imu_fusion::cloud_img_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_imu_fusion::cloud_img_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_imu_fusion::cloud_img_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abb846272076f986f29cdb4304809722";
  }

  static const char* value(const ::lidar_imu_fusion::cloud_img_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xabb846272076f986ULL;
  static const uint64_t static_value2 = 0xf29cdb4304809722ULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_imu_fusion::cloud_img_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_imu_fusion/cloud_img";
  }

  static const char* value(const ::lidar_imu_fusion::cloud_img_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_imu_fusion::cloud_img_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header \n"
"sensor_msgs/PointCloud2 local_map\n"
"sensor_msgs/Image img\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
;
  }

  static const char* value(const ::lidar_imu_fusion::cloud_img_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_imu_fusion::cloud_img_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.local_map);
      stream.next(m.img);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cloud_img_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_imu_fusion::cloud_img_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_imu_fusion::cloud_img_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "local_map: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.local_map);
    s << indent << "img: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.img);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_IMU_FUSION_MESSAGE_CLOUD_IMG_H
