// Generated by gencpp from file lidar_imu_fusion/reset_lidar_odometryResponse.msg
// DO NOT EDIT!


#ifndef LIDAR_IMU_FUSION_MESSAGE_RESET_LIDAR_ODOMETRYRESPONSE_H
#define LIDAR_IMU_FUSION_MESSAGE_RESET_LIDAR_ODOMETRYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lidar_imu_fusion
{
template <class ContainerAllocator>
struct reset_lidar_odometryResponse_
{
  typedef reset_lidar_odometryResponse_<ContainerAllocator> Type;

  reset_lidar_odometryResponse_()
    : resetCloudTime(0.0)
    , success(false)  {
    }
  reset_lidar_odometryResponse_(const ContainerAllocator& _alloc)
    : resetCloudTime(0.0)
    , success(false)  {
  (void)_alloc;
    }



   typedef double _resetCloudTime_type;
  _resetCloudTime_type resetCloudTime;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::lidar_imu_fusion::reset_lidar_odometryResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_imu_fusion::reset_lidar_odometryResponse_<ContainerAllocator> const> ConstPtr;

}; // struct reset_lidar_odometryResponse_

typedef ::lidar_imu_fusion::reset_lidar_odometryResponse_<std::allocator<void> > reset_lidar_odometryResponse;

typedef boost::shared_ptr< ::lidar_imu_fusion::reset_lidar_odometryResponse > reset_lidar_odometryResponsePtr;
typedef boost::shared_ptr< ::lidar_imu_fusion::reset_lidar_odometryResponse const> reset_lidar_odometryResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_imu_fusion::reset_lidar_odometryResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_imu_fusion::reset_lidar_odometryResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lidar_imu_fusion::reset_lidar_odometryResponse_<ContainerAllocator1> & lhs, const ::lidar_imu_fusion::reset_lidar_odometryResponse_<ContainerAllocator2> & rhs)
{
  return lhs.resetCloudTime == rhs.resetCloudTime &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lidar_imu_fusion::reset_lidar_odometryResponse_<ContainerAllocator1> & lhs, const ::lidar_imu_fusion::reset_lidar_odometryResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lidar_imu_fusion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lidar_imu_fusion::reset_lidar_odometryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_imu_fusion::reset_lidar_odometryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_imu_fusion::reset_lidar_odometryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_imu_fusion::reset_lidar_odometryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_imu_fusion::reset_lidar_odometryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_imu_fusion::reset_lidar_odometryResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_imu_fusion::reset_lidar_odometryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e022d1b9330aaf6ba11eadd9100365c";
  }

  static const char* value(const ::lidar_imu_fusion::reset_lidar_odometryResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e022d1b9330aaf6ULL;
  static const uint64_t static_value2 = 0xba11eadd9100365cULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_imu_fusion::reset_lidar_odometryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_imu_fusion/reset_lidar_odometryResponse";
  }

  static const char* value(const ::lidar_imu_fusion::reset_lidar_odometryResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_imu_fusion::reset_lidar_odometryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 resetCloudTime\n"
"bool success\n"
;
  }

  static const char* value(const ::lidar_imu_fusion::reset_lidar_odometryResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_imu_fusion::reset_lidar_odometryResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.resetCloudTime);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct reset_lidar_odometryResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_imu_fusion::reset_lidar_odometryResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_imu_fusion::reset_lidar_odometryResponse_<ContainerAllocator>& v)
  {
    s << indent << "resetCloudTime: ";
    Printer<double>::stream(s, indent + "  ", v.resetCloudTime);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_IMU_FUSION_MESSAGE_RESET_LIDAR_ODOMETRYRESPONSE_H
